services:
  - type: web
    name: sentiment-analyzer-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: hmhh00-Key
        sync: false